# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tweet

on:
  workflow_dispatch:
  schedule:
    # UTC 03:00 = KST 12:00
    - cron: '0 3 * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        cache: 'yarn'
    - run: yarn
    - run: node --unhandled-rejections=strict index.js
      env:
        OPEN_API_SERVICE_KEY: ${{ secrets.OPEN_API_SERVICE_KEY }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
